<a href="https://colab.research.google.com/github/KithusshandR/ML_Assignment2_IT19029832_IT19241760_IT19121802/blob/Development/ML_Assignment02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Necessary Libraries

The nltk library to proecess the text and the pandas library to load the data are loaded.

In [ ]:
#load the libraries
import nltk
import pandas as pd

# Load Data

Load the dataset 

In [108]:
#load data from the github repository 
#pre-request the repository needs to be public
# dataset = pd.read_csv('https://github.com/KithusshandR/ML_Assignment2_IT19029832_IT19241760_IT19121802/blob/main/website_classification.csv') 

#load data from google drive
from google.colab import drive
drive.mount('/content/gdrive')

dataset = pd.read_csv('/content/gdrive/MyDrive/content/website_classification.csv')

dataset.head()

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


Unnamed: 0                                        website_url  \
0           0     https://www.booking.com/index.html?aid=1743217   
1           1                   https://travelsites.com/expedia/   
2           2               https://travelsites.com/tripadvisor/   
3           3              https://www.momondo.in/?ispredir=true   
4           4  https://www.ebookers.com/?AFFCID=EBOOKERS-UK.n...   

                                cleaned_website_text Category  
0  official site good hotel accommodation big sav...   Travel  
1  expedia hotel book sites like use vacation wor...   Travel  
2  tripadvisor hotel book sites like previously d...   Travel  
3  cheap flights search compare flights momondo f...   Travel  
4  bot create free account create free account si...   Travel

# Analysis the loaded Dataset

The loaded dataset is analysised to find the information about the dataset like No of row and no of columns

In [ ]:
#find the dataset number of rows and columns
dataset.shape

(1408, 4)

In [ ]:
#print the dataset columns names
dataset.columns

Index(['Unnamed: 0', 'website_url', 'cleaned_website_text', 'Category'], dtype='object')

In [109]:
#drop the first column (ID column)
dataset = dataset.drop('Unnamed: 0', axis=1)
dataset = dataset.drop('website_url', axis=1)
dataset.head()

cleaned_website_text Category
0  official site good hotel accommodation big sav...   Travel
1  expedia hotel book sites like use vacation wor...   Travel
2  tripadvisor hotel book sites like previously d...   Travel
3  cheap flights search compare flights momondo f...   Travel
4  bot create free account create free account si...   Travel

In [110]:
#find the datatype
dataset.dtypes

cleaned_website_text    object
Category                object
dtype: object

In [111]:
#find the fact about the dataset e.g: Datatype and count
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1408 entries, 0 to 1407
Data columns (total 2 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   cleaned_website_text  1408 non-null   object
 1   Category              1408 non-null   object
dtypes: object(2)
memory usage: 22.1+ KB


# Data Preprocessing

The Data preprocessing is used to clean the data like removeing the null values and duplicate values and prepare the dataset to train the machine learning model.

In [112]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
lemmartizer = WordNetLemmatizer()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [113]:
#create a function to tokenize the words and use lemmartizer to lemmatize the word
def tokenize(text):
  #lemmatize the words
  text = lemmartizer.lemmatize(text)
  #create the text into word tokens
  tokens = nltk.word_tokenize(text)
  return tokens

In [114]:
#add some stopwords that needs to remove
nltk_stop_words = set(stopwords.words('english'))
nltk_stop_words.update(["'d", "'ll", "'re", "'s", "'ve", 'could', 'doe', 'ha', 'might', 'must', "n't", 'need', 'sha', 'wa', 'wo', 'would'])

In [115]:
from sklearn.feature_extraction.text import CountVectorizer

#use the count Vectorizer to vectorize the text.
countvectorizer = CountVectorizer(min_df=1, tokenizer=tokenize, stop_words=nltk_stop_words)

#create a dataframe
dtm = pd.DataFrame(countvectorizer.fit_transform(dataset['cleaned_website_text']).toarray(),
                                                 columns=countvectorizer.get_feature_names(), index=None)


#check the dataframe
dtm.head()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


-pron-  007f  0084ff  00s  01b  01st  02000f  02001f  02005f  03rd  ...  \
0       0     0       0    0    0     0       0       0       0     0  ...   
1       0     0       0    0    0     0       0       0       0     0  ...   
2       0     0       0    0    0     0       0       0       0     0  ...   
3       0     0       0    0    0     0       0       0       0     0  ...   
4       0     0       0    0    0     0       0       0       0     0  ...   

   카메라  한국  한국어  현미경용  𝐂  𝐅𝐎𝐑  𝐅𝐔𝐋𝐋𝐘  𝐋𝐎𝐀𝐃𝐄𝐃  𝐎𝐏𝐄𝐍  𝐓𝐀𝐊𝐄𝐀  
0    0   0    1     0  0    0      0       0     0      0  
1    0   0    0     0  0    0      0       0     0      0  
2    0   0    0     0  0    0      0       0     0      0  
3    0   0    0     0  0    0      0       0     0      0  
4    0   0    0     0  0    0      0       0     0      0  

[5 rows x 60061 columns]

In [116]:
#print the dataframe row number anc column number
dtm.shape

(1408, 60061)

In [117]:
#Use the Encoder to encoding the lable
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
lable = le.fit_transform(dataset.Category)

In [118]:
#check the Categories that encoded
print(lable)

[15 15 15 ...  0  0  0]


In [119]:
# train and test dataset split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(dtm, lable, 
                                     train_size = 0.7, 
                                     test_size = 0.3, 
                                     random_state = 100,
                                     stratify = lable)

In [120]:
X_train

-pron-  007f  0084ff  00s  01b  01st  02000f  02001f  02005f  03rd  ...  \
71         0     0       0    0    0     0       0       0       0     0  ...   
762        0     0       0    0    0     0       0       0       0     0  ...   
1146       0     0       0    0    0     0       0       0       0     0  ...   
710        0     0       0    0    0     0       0       0       0     0  ...   
1352       0     0       0    0    0     0       0       0       0     0  ...   
...      ...   ...     ...  ...  ...   ...     ...     ...     ...   ...  ...   
1107       0     0       0    0    0     0       0       0       0     0  ...   
115        0     0       0    0    0     0       0       0       0     0  ...   
250        0     0       0    0    0     0       0       0       0     0  ...   
254        0     0       0    0    0     0       0       0       0     0  ...   
470        0     0       0    0    0     0       0       0       0     0  ...   

      카메라  한국  한국어  현미경용  𝐂  𝐅𝐎𝐑  𝐅𝐔𝐋𝐋𝐘  𝐋𝐎𝐀𝐃𝐄𝐃  𝐎𝐏𝐄𝐍  𝐓𝐀𝐊𝐄𝐀  
71      0   0    0     0  0    0      0       0     0      0  
762     0   0    0     0  0    0      0       0     0      0  
1146    0   0    0     0  0    0      0       0     0      0  
710     0   0    0     0  0    0      0       0     0      0  
1352    0   0    0     0  0    0      0       0     0      0  
...   ...  ..  ...   ... ..  ...    ...     ...   ...    ...  
1107    0   0    0     0  0    0      0       0     0      0  
115     0   0    0     0  0    0      0       0     0      0  
250     0   0    0     0  0    0      0       0     0      0  
254     0   0    0     0  0    0      0       0     0      0  
470     0   0    0     0  0    0      0       0     0      0  

[985 rows x 60061 columns]

In [121]:
y_train

array([15,  8,  3,  8,  1,  7, 13,  5, 10, 11, 15,  3,  1,  2,  7, 10,  3,
       14,  2, 13,  3, 10, 13,  7,  3, 14,  1,  8, 10,  4,  7,  5,  7,  3,
        4,  8, 14,  3, 11, 13,  5,  1,  3,  8, 14, 14, 15,  4,  4,  6,  4,
       12,  7,  7, 13,  7,  9,  1,  2, 13,  8, 10, 14, 12, 13,  9,  9,  3,
        4, 11,  4, 14, 12, 11,  8,  3,  7,  4,  1, 10,  1,  8, 13, 13, 11,
        2,  9,  2,  5,  1,  5,  7,  1,  8,  1, 11,  5,  8, 11,  5,  7,  3,
       12,  8,  3, 10,  4, 13, 11,  1,  3,  5, 11, 11,  4,  2, 13,  4, 10,
       12,  5, 12, 11,  9, 14, 13,  8,  9,  8,  7,  2,  5, 11,  9, 11,  5,
       14, 15, 11, 13,  1,  2, 15,  8, 12,  2,  3, 13,  7, 10, 15, 14,  7,
       12,  7, 14, 12,  2, 10,  9, 10, 14, 15, 13, 13,  8,  9, 15,  4,  4,
       15,  7, 13,  7, 14,  8, 11,  4, 15, 10,  1,  9,  9,  8,  4,  4, 12,
        9, 14, 13, 10,  9, 13, 15,  1,  2,  9,  6,  4, 11,  4,  3,  3,  4,
       14, 12,  3,  7, 11,  7,  9, 15, 11, 11, 15,  9,  7,  1, 13, 11,  4,
        2,  8, 11,  2,  5

# Machine Learning model

Here we use teh Multinomial Naive Bayes Model to train the model

In [122]:
# Train the model 
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [124]:
#predict the X_test
prediction = model.predict(X_test)
prediction

array([10, 14, 12,  8,  3,  3,  4, 14, 12,  7, 10, 15,  8,  8, 14, 14,  1,
       10,  4,  1,  4,  3, 12, 10, 11, 14, 12, 15, 13,  4, 13, 11,  0,  2,
        7, 14,  9,  5,  9,  9,  1, 13,  3, 13,  4, 15, 11, 11,  3,  0,  5,
        3,  1, 10, 15,  2, 11,  4,  3, 15, 12,  7,  1,  5,  1, 13,  9,  4,
       10,  1,  5,  2,  8,  7,  5,  7,  1,  1,  2,  1, 12, 10, 12, 11, 10,
       15,  7, 11,  5, 10, 13, 15, 14,  7,  2, 10, 13,  2, 12, 12,  9,  7,
        1,  3,  7, 15, 12,  1, 14,  1, 10,  2,  8, 11,  2,  2,  5, 14,  8,
        4, 13,  5, 15,  1,  8,  8,  4, 10, 14,  5,  5,  2,  4, 15, 13, 10,
        3, 13,  4, 13,  0,  1,  7,  3, 15, 14, 12,  2, 14, 11, 13, 10,  3,
       11,  9, 14,  7, 13, 15,  2,  1,  7, 14,  5,  7,  4,  2,  8,  9, 13,
        5,  3,  8,  2,  3,  7,  7,  2, 15,  9, 13,  7, 13, 14,  8, 15,  9,
        8,  2, 14,  4,  9, 11,  4,  8,  1,  5,  4, 10,  4,  5, 14, 10,  3,
        7, 11, 10,  2, 13, 13,  8, 11, 13, 13, 15,  8, 10,  9, 15,  9, 10,
       11,  2,  3,  3, 15

# Test the model

Test the model and print the accuracy of the created machine learning model

In [125]:
#print the actual label to compare with the prediction
y_test

array([10, 14, 12,  8,  3,  3,  4, 14, 12,  7, 10, 15, 15,  8, 14, 14,  1,
        5,  4,  1,  4,  0, 12,  6, 11, 12, 12, 15, 13,  4, 13, 11,  0,  2,
        7, 14,  9,  5,  9,  9,  1,  6,  3, 13,  4, 15, 11, 11,  3,  0,  5,
        1,  1, 10, 15,  2, 11,  4,  3, 15, 12,  7,  1,  5,  1, 13,  4,  4,
       10,  1,  5,  2,  8,  7,  5,  1,  1,  1,  2,  1,  6,  8, 12, 12, 10,
       15,  7, 11,  5, 10, 13, 15, 14,  7,  2,  8, 13,  2, 12, 12,  9,  7,
        1,  3,  7, 15, 12,  4, 14,  1, 10,  2,  8, 11,  2,  2,  5, 14,  8,
        4, 13,  5, 15,  1,  8,  8,  4, 10, 14,  5,  5,  7,  4, 15, 13,  2,
        1,  7,  2, 13,  0,  1,  7,  3, 15, 14, 12, 12,  9, 12, 13,  9,  1,
       11,  9, 14,  7, 13, 15,  2,  1,  7, 14,  5,  7,  4,  2,  8,  9, 13,
        5,  3,  8,  2,  3,  7,  7,  2, 15,  9, 13,  7, 13, 14,  8, 15,  9,
        8,  2, 14,  4,  8, 11,  4,  8,  1,  5,  4, 10,  4,  5, 14,  1,  3,
        7, 11, 10,  2, 10, 13,  8, 11, 13, 13, 15,  8,  6,  1, 15,  9, 10,
       11,  2,  3,  3, 15

In [127]:
#print the training accuracy and the testing accuracy
from sklearn.metrics import accuracy_score

print('The mode training accuracy:', round(accuracy_score(y_train, model.predict(X_train)),5))
print('The model Testing accuracy:', round(accuracy_score(y_test, prediction),5))

The mode training accuracy: 0.98376
The model Testing accuracy: 0.88416


In [129]:
#Test the created model
import numpy as np
new_text = np.array(["She is very hot and sexy"])

new_vector = countvectorizer.transform(new_text)
print(le.inverse_transform(model.predict(new_vector)))

['Adult']


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  "X does not have valid feature names, but"
